config/routes.rb
Traffic::Application.routes.draw do
  resources :users
  resources :maps,     only: [:update]
  resources :sessions, only: [:new, :create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  root 'static_pages#home'

  

end

app/models/map.rb
class Map < ActiveRecord::Base
  after_initialize :default_map_values

  private

    def default_map_values
      self.lat ||= 38.8951
      self.lon ||= -77.0367
      self.zoom ||= 11
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :map, dependent: :destroy

  before_save { self.email = email.downcase }
  before_create :create_token_and_map

  validates :name,  presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 8 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_token_and_map
      self.remember_token = User.encrypt(User.new_remember_token)
      self.map_id = Map.create().id
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :signed_in_user, only: [:update]
  before_action :correct_user,   only: [:update]

  def update
    @map = Map.find(params[:id])
    if @map.update_attributes(map_params)
      flash[:success] = "Map updated"
      redirect_to current_user
    else
      flash[:error] = "Error, please try again"
      redirect_to current_user
    end
  end

  private

    def map_params
      params.require(:map).permit(:lat, :lon, :zoom, :traffic, :weather)
    end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      redirect_to(root_url) unless current_user.map_id.to_s == params[:id].to_s
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @map = Map.find(@user.map_id)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the site!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # Before filters

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return map head if map is present
  def map_head(map)
    if !map.empty?
      render 'layouts/map'
    end
  end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    &copy; Daniel Bryant
  </small>
</footer>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
   <div class="navbar-inner">
     <div class="container">
       <%= link_to "myTraffic", root_path, id: "logo" %>
       <nav>
         <ul class="nav pull-right">
           <li><%= link_to "Home",    root_path %></li>
           <% if signed_in? %>
             <li><%= link_to "Users", users_path %></li>
             <li id="fat-menu" class="dropdown">
               <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                 Account <b class="caret"></b>
               </a>
               <ul class="dropdown-menu">
                 <li><%= link_to "Profile", current_user %></li>
                 <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                 <li class="divider"></li>
                 <li>
                   <%= link_to "Sign out", signout_path, method: "delete" %>
                 </li>
               </ul>
             </li>
           <% else %>
             <li><%= link_to "Sign in", signin_path %></li>
           <% end %>
         </ul>
       </nav>
     </div>
   </div>
 </header>

app/views/layouts/_map.html.erb
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDI0bE0M9JZX4ieLHZmhS6NW0a62qkLhko&sensor=false&libraries=weather">
    </script>
    <%= javascript_tag do %>
      function initialize() {

        var lat =  <%= Map.find(current_user.map_id).lat.html_safe %>;
        var lon =  <%= Map.find(current_user.map_id).lon.html_safe %>;
        var zoom = <%= Map.find(current_user.map_id).zoom.html_safe %>;

        var mapOptions = {
          center: new google.maps.LatLng(lat, lon),
          zoom: zoom,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("map-canvas"),
            mapOptions);

        <% if Map.find(current_user.map_id).traffic? %>
          var trafficLayer = new google.maps.TrafficLayer();
          trafficLayer.setMap(map);
        <% end %>


        <% if Map.find(current_user.map_id).weather? %>
          var weatherLayer = new google.maps.weather.WeatherLayer({
            temperatureUnits: google.maps.weather.TemperatureUnit.FAHRENHEIT
          });
          weatherLayer.setMap(map);

          var cloudLayer = new google.maps.weather.CloudLayer();
          cloudLayer.setMap(map);
        <% end %>

        google.maps.event.addListener(map, 'center_changed', function() {
          document.getElementById('map_lat').value = map.getCenter().lat();
          document.getElementById('map_lon').value = map.getCenter().lng();
        });

        google.maps.event.addListener(map, 'zoom_changed', function() {
          document.getElementById('map_zoom').value = map.getZoom();
        });

      }
      google.maps.event.addDomListener(window, 'load', initialize);
    <% end %>

app/views/layouts/_shim.html.erb
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]--> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>myTraffic</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <%= map_head(yield(:map)) %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the myTraffic Web App</h1>
  <p>by <a href="https://github.com/daniel-bryant" target="_blank">Daniel Bryant</a></p>
  <% if !signed_in? %>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
    </li>
    <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete,
                                    data: { confirm: "You sure?" } %>
    <% end %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:map, 'map') %>
<h1>
  Welcome <%= @user.name %>, Safe Travels
</h1>

<div id="map-canvas"></div>

<div class="map-save">
  <div style="height: 30px">
    Traffic
    <% if @map.traffic? %>
      <input type="checkbox" id="check_t" name="check_t" onclick="toggle_t();" checked>
    <% else %>
      <input type="checkbox" id="check_t" name="check_t" onclick="toggle_t();">
    <% end %>
    Weather
    <% if @map.weather? %>
      <input type="checkbox" id="check_w" name="check_w" onclick="toggle_w();" checked>
    <% else %>
      <input type="checkbox" id="check_w" name="check_w" onclick="toggle_w();">
    <% end %>

    <div style="float:right;">
      <a href="#" class="btn btn-success" onClick="window.location.reload()"><i class="icon-white icon-refresh"></i></a>
    </div>
  </div>

  <%= form_for (@map) do |f| %>

    <%= f.hidden_field :lat %>
    <%= f.hidden_field :lon %>
    <%= f.hidden_field :zoom %>
    <%= f.hidden_field :traffic %>
    <%= f.hidden_field :weather %>

    <%= f.submit "Update Map", class: "btn btn-primary" %>
  <% end %>
</div>

<%= javascript_tag do %>
  function toggle_t()
  {
    if(document.getElementById('check_t').checked)
      document.getElementById('map_traffic').value = 't';
    else
      document.getElementById('map_traffic').value = 'f';
  }

  function toggle_w()
  {
    if(document.getElementById('check_w').checked)
      document.getElementById('map_weather').value = 't';
    else
      document.getElementById('map_weather').value = 'f';
  }
<% end %>